//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emaratech.Services.Scheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobParameters = new HashSet<JobParameter>();
        }
    
        public string Id { get; set; }
        public string JobId { get; set; }
        public string Name { get; set; }
        public string JobType { get; set; }
        public long Version { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string CloneSourceId { get; set; }
        public Nullable<decimal> CloneSourceVersion { get; set; }
        public Nullable<decimal> RevertedFromVersion { get; set; }
        public bool IsActive { get; set; }
        public bool IsLocked { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public bool IsExecuted { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public string ExecutedBy { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> MaxLockSeconds { get; set; }
    
        public virtual ICollection<JobParameter> JobParameters { get; set; }
    }
}
