//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emaratech.Services.Scheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobParameter
    {
        public string JobId { get; set; }
        public long StartVersion { get; set; }
        public Nullable<long> EndVersion { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
