//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emaratech.Services.Scheduler.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSource
    {
        public string Id { get; set; }
        public string Class { get; set; }
        public string Process { get; set; }
        public string API { get; set; }
        public byte[] Content { get; set; }
        public string JobId { get; set; }
    }
}
