//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Emaratech.DatabaseLayer;

namespace Emaratech.Services.Scheduler.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerContext : BaseContext<SchedulerContext>
    {
        public SchedulerContext()
            : base("name=SchedulerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Job> Jobs1 { get; set; }
        public DbSet<JobSchedule> JobSchedules { get; set; }
        public DbSet<JobSource> JobSources { get; set; }
        public DbSet<ScheduleType> ScheduleTypes { get; set; }
        public DbSet<SystemJob> SystemJobs { get; set; }
        public DbSet<JobParameter> JobParameters1 { get; set; }
        public DbSet<JobInstance> JobInstances { get; set; }
        public DbSet<JobLock> JobLocks { get; set; }
    }
}
