ALTER SESSION SET CURRENT_SCHEMA=ECORE_SCHEDULER; 

ALTER TABLE "JOB_SCHEDULE"
ADD (
	START_DATE TIMESTAMP
);

ALTER TABLE "JOB_SCHEDULE"
MODIFY (
	SCHEDULE_FREQUENCY INT DEFAULT 1
);

ALTER TABLE "JOB_SCHEDULE" DROP CONSTRAINT "FK_JOB_SCHEDULE_JOB";