ALTER SESSION SET CURRENT_SCHEMA=ECORE_SCHEDULER; 

CREATE OR REPLACE TRIGGER TRG_DB_VERSION_ID BEFORE INSERT ON DB_VERSION FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_DB_VERSION.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;

  IF :NEW.APPLIED_BY IS NULL THEN
    SELECT USER INTO :NEW.APPLIED_BY FROM DUAL;
  END IF;

  IF :NEW.APPLIED_DATE IS NULL THEN
    SELECT CURRENT_TIMESTAMP INTO :NEW.APPLIED_DATE FROM DUAL;
  END IF;
END;
/

