ALTER SESSION SET CURRENT_SCHEMA=ECORE_SCHEDULER; 

ALTER TABLE "JOB_SOURCE"
MODIFY (
	CLASS	NULL,
	PROCESS	NULL,
	API	NULL
);

ALTER TABLE "JOB_SOURCE"
ADD (
	CONTENT	BLOB,
	JOB_ID	NVARCHAR2(32) NOT NULL
);

ALTER TABLE "JOB_SOURCE" DROP CONSTRAINT "FK_JOB_SOURCE_JOB";