--
-- New user
--
ALTER SESSION SET CURRENT_SCHEMA = SYS;

--new user
ALTER SESSION SET "_ORACLE_SCRIPT"=true; -- to avoid "invalid common user or role name" error

CREATE USER ECORE_SCHEDULER IDENTIFIED BY "q1w2e3";
ALTER USER ECORE_SCHEDULER QUOTA UNLIMITED ON USERS;

ALTER USER ECORE_SCHEDULER DEFAULT TABLESPACE USERS;

GRANT CONNECT TO ECORE_SCHEDULER;

--new user's permissions
GRANT CREATE SESSION TO ECORE_SCHEDULER;
GRANT CREATE TABLE TO ECORE_SCHEDULER;
GRANT CREATE VIEW TO ECORE_SCHEDULER;
GRANT CREATE ANY TRIGGER TO ECORE_SCHEDULER;
GRANT CREATE ANY PROCEDURE TO ECORE_SCHEDULER;
GRANT CREATE SEQUENCE TO ECORE_SCHEDULER;
GRANT CREATE SYNONYM TO ECORE_SCHEDULER;
GRANT CREATE PUBLIC SYNONYM TO ECORE_SCHEDULER;
GRANT CREATE TYPE TO ECORE_SCHEDULER;



--
-- Rollback
--
--drop user with schema
ALTER SESSION SET CURRENT_SCHEMA = SYS;

DROP USER ECORE_SCHEDULER CASCADE;
