ALTER SESSION SET CURRENT_SCHEMA=ECORE_SCHEDULER; 

ALTER TABLE "JOB_INSTANCE"
MODIFY (
	LOCKED_BY	NULL,
	LOCKED_DATE	NULL,
	EXECUTED_DATE	NULL,
	EXECUTED_BY	NULL
);

ALTER TABLE "JOB_INSTANCE" 
DROP (
  IS_LOCKED,
  LOCKED_BY,
  LOCKED_DATE
);

ALTER TABLE "JOB_INSTANCE" DROP CONSTRAINT "FK_JOB_INSTANCE_JOB";