ALTER SESSION SET CURRENT_SCHEMA=ECORE_SCHEDULER; 

CREATE OR REPLACE FUNCTION CURRENT_DB_VERSION
RETURN NUMBER
IS RESULT NUMBER;
BEGIN
  SELECT VERSION INTO RESULT FROM (
    SELECT VERSION FROM DB_VERSION WHERE SUCCESS = 1 ORDER BY APPLIED_DATE DESC
  ) WHERE ROWNUM = 1;

  RETURN RESULT;
END;
/

